services:
  continuwuity:
    image: registry.gitlab.com/continuwuity/continuwuity:latest
    restart: unless-stopped
    networks:
      continuwuity_network:
        gw_priority: 0
      tipi_main_network:
        gw_priority: 1
    environment:
      CONDUIT_SERVER_NAME: ${APP_DOMAIN}
      CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
      CONDUIT_DATABASE_BACKEND: rocksdb
      CONDUIT_ADDRESS: 0.0.0.0
      CONDUIT_PORT: "6167"
      CONDUIT_LOG: info
      CONDUIT_MAX_REQUEST_SIZE: ${MAX_REQUEST_SIZE:-20000000}
      CONDUIT_ALLOW_REGISTRATION: ${ALLOW_REGISTRATION:-false}
      CONDUIT_REGISTRATION_TOKEN: ${REGISTRATION_TOKEN}
      CONDUIT_YES_I_AM_VERY_VERY_SURE_I_WANT_AN_OPEN_REGISTRATION_SERVER_PRONE_TO_ABUSE: ${ALLOW_REGISTRATION:-false}
      CONDUIT_ALLOW_FEDERATION: ${ALLOW_FEDERATION:-true}
      CONDUIT_TRUSTED_SERVERS: ${TRUSTED_SERVERS:-[]}
      CONDUIT_ALLOW_CHECK_FOR_UPDATES: "false"
      # Enhanced presence configuration (Continuwuity's advanced features)
      CONDUIT_ALLOW_LOCAL_PRESENCE: "true"
      CONDUIT_ALLOW_INCOMING_PRESENCE: "true"
      CONDUIT_ALLOW_OUTGOING_PRESENCE: "true"
      CONDUIT_CONFIG: ""
      # TURN server configuration
      CONDUIT_TURN_URIS: '[\"turn:${APP_DOMAIN}:3478?transport=udp\", \"turn:${APP_DOMAIN}:3478?transport=tcp\", \"turns:${APP_DOMAIN}:5349?transport=tcp\"]'
      CONDUIT_TURN_SECRET: "${TURN_SECRET}"
      CONDUIT_TURN_USERNAME: ""
      CONDUIT_TURN_TTL: "86400"
      # Database recovery options for troubleshooting
      CONDUIT_DATABASE_RECOVERY_MODE: ${DATABASE_RECOVERY_MODE:-2}
      CONDUIT_DATABASE_REPAIR: ${DATABASE_REPAIR_MODE:-false}
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/matrix-conduit/
    depends_on:
      - coturn
    labels:
      runtipi.managed: true
      traefik.enable: ${APP_EXPOSED}
      traefik.http.middlewares.${APP_ID}-continuwuity-web-redirect.redirectscheme.scheme: https
      traefik.http.services.${APP_ID}-continuwuity.loadbalancer.server.port: "6167"
      traefik.http.routers.${APP_ID}-continuwuity-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.${APP_ID}-continuwuity-insecure.entrypoints: web
      traefik.http.routers.${APP_ID}-continuwuity-insecure.service: ${APP_ID}-continuwuity
      traefik.http.routers.${APP_ID}-continuwuity-insecure.priority: 100
      traefik.http.routers.${APP_ID}-continuwuity.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.${APP_ID}-continuwuity.entrypoints: websecure
      traefik.http.routers.${APP_ID}-continuwuity.service: ${APP_ID}-continuwuity
      traefik.http.routers.${APP_ID}-continuwuity.tls.certresolver: myresolver
      traefik.http.routers.${APP_ID}-continuwuity.priority: 100
      traefik.http.routers.${APP_ID}-continuwuity-local-insecure.rule: Host(`${APP_ID}.${LOCAL_DOMAIN}`)
      traefik.http.routers.${APP_ID}-continuwuity-local-insecure.entrypoints: web
      traefik.http.routers.${APP_ID}-continuwuity-local-insecure.service: ${APP_ID}-continuwuity
      traefik.http.routers.${APP_ID}-continuwuity-local-insecure.middlewares: ${APP_ID}-continuwuity-web-redirect@docker
      traefik.http.routers.${APP_ID}-continuwuity-local.rule: Host(`${APP_ID}.${LOCAL_DOMAIN}`)
      traefik.http.routers.${APP_ID}-continuwuity-local.entrypoints: websecure
      traefik.http.routers.${APP_ID}-continuwuity-local.service: ${APP_ID}-continuwuity
      traefik.http.routers.${APP_ID}-continuwuity-local.tls: "true"

  continuwuity-well-known:
    image: nginx
    restart: unless-stopped
    networks:
      continuwuity_network:
        gw_priority: 0
      tipi_main_network:
        gw_priority: 1
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
    volumes:
      - ./nginx:/etc/nginx/templates
    labels:
      runtipi.managed: true
      traefik.enable: ${APP_EXPOSED}
      traefik.http.middlewares.${APP_ID}-well-known-web-redirect.redirectscheme.scheme: https
      traefik.http.services.${APP_ID}-well-known.loadbalancer.server.port: "80"
      traefik.http.routers.${APP_ID}-well-known-insecure.rule: Host(`${APP_DOMAIN}`) && PathPrefix(`/.well-known/matrix/`)
      traefik.http.routers.${APP_ID}-well-known-insecure.entrypoints: web
      traefik.http.routers.${APP_ID}-well-known-insecure.service: ${APP_ID}-well-known
      traefik.http.routers.${APP_ID}-well-known-insecure.priority: 100
      traefik.http.routers.${APP_ID}-well-known.rule: Host(`${APP_DOMAIN}`) && PathPrefix(`/.well-known/matrix/`)
      traefik.http.routers.${APP_ID}-well-known.entrypoints: websecure
      traefik.http.routers.${APP_ID}-well-known.service: ${APP_ID}-well-known
      traefik.http.routers.${APP_ID}-well-known.tls.certresolver: myresolver
      traefik.http.routers.${APP_ID}-well-known.priority: 100
      traefik.http.routers.${APP_ID}-well-known-local-insecure.rule: Host(`${APP_ID}.${LOCAL_DOMAIN}`) && PathPrefix(`/.well-known/matrix/`)
      traefik.http.routers.${APP_ID}-well-known-local-insecure.entrypoints: web
      traefik.http.routers.${APP_ID}-well-known-local-insecure.service: ${APP_ID}-well-known
      traefik.http.routers.${APP_ID}-well-known-local-insecure.middlewares: ${APP_ID}-well-known-web-redirect@docker
      traefik.http.routers.${APP_ID}-well-known-local.rule: Host(`${APP_ID}.${LOCAL_DOMAIN}`) && PathPrefix(`/.well-known/matrix/`)
      traefik.http.routers.${APP_ID}-well-known-local.entrypoints: websecure
      traefik.http.routers.${APP_ID}-well-known-local.service: ${APP_ID}-well-known
      traefik.http.routers.${APP_ID}-well-known-local.tls: "true"

  # LiveKit server for Element Call video conferencing
  livekit:
    image: livekit/livekit-server:v1.7.2
    restart: unless-stopped
    networks:
      continuwuity_network:
        gw_priority: 0
      tipi_main_network:
        gw_priority: 1
    ports:
      - "7880:7880"  # HTTP
      - "7881:7881"  # HTTPS
      - "7882:7882/udp"  # TURN/UDP
      - "50000-50200:50000-50200/udp"  # WebRTC UDP range
    command: --config /livekit.yaml --bind 0.0.0.0
    environment:
      LIVEKIT_DOMAIN: ${APP_DOMAIN}
    volumes:
      - ./livekit.yaml:/livekit.yaml:ro
    labels:
      runtipi.managed: true
      traefik.enable: ${APP_EXPOSED}
      traefik.http.middlewares.${APP_ID}-livekit-stripprefix.stripprefix.prefixes: /livekit
      traefik.http.services.${APP_ID}-livekit.loadbalancer.server.port: "7880"
      traefik.http.routers.${APP_ID}-livekit-insecure.rule: Host(`${APP_DOMAIN}`) && PathPrefix(`/livekit`)
      traefik.http.routers.${APP_ID}-livekit-insecure.entrypoints: web
      traefik.http.routers.${APP_ID}-livekit-insecure.service: ${APP_ID}-livekit
      traefik.http.routers.${APP_ID}-livekit-insecure.middlewares: ${APP_ID}-livekit-stripprefix@docker
      traefik.http.routers.${APP_ID}-livekit-insecure.priority: 75
      traefik.http.routers.${APP_ID}-livekit.rule: Host(`${APP_DOMAIN}`) && PathPrefix(`/livekit`)
      traefik.http.routers.${APP_ID}-livekit.entrypoints: websecure
      traefik.http.routers.${APP_ID}-livekit.service: ${APP_ID}-livekit
      traefik.http.routers.${APP_ID}-livekit.tls.certresolver: myresolver
      traefik.http.routers.${APP_ID}-livekit.middlewares: ${APP_ID}-livekit-stripprefix@docker
      traefik.http.routers.${APP_ID}-livekit.priority: 75

  # LiveKit JWT service for Element Call authentication
  livekit-jwt:
    image: ghcr.io/element-hq/lk-jwt-service:latest
    restart: unless-stopped
    networks:
      continuwuity_network:
        gw_priority: 0
      tipi_main_network:
        gw_priority: 1
    environment:
      - LIVEKIT_URL=wss://${APP_DOMAIN}/livekit
      - LIVEKIT_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_SECRET=${LIVEKIT_API_SECRET}
      - MATRIX_SERVER_NAME=${APP_DOMAIN}
    labels:
      runtipi.managed: true
      traefik.enable: ${APP_EXPOSED}
      traefik.http.middlewares.${APP_ID}-livekit-jwt-stripprefix.stripprefix.prefixes: /livekit-jwt
      traefik.http.services.${APP_ID}-livekit-jwt.loadbalancer.server.port: "8080"
      traefik.http.routers.${APP_ID}-livekit-jwt-insecure.rule: Host(`${APP_DOMAIN}`) && PathPrefix(`/livekit-jwt`)
      traefik.http.routers.${APP_ID}-livekit-jwt-insecure.entrypoints: web
      traefik.http.routers.${APP_ID}-livekit-jwt-insecure.service: ${APP_ID}-livekit-jwt
      traefik.http.routers.${APP_ID}-livekit-jwt-insecure.middlewares: ${APP_ID}-livekit-jwt-stripprefix@docker
      traefik.http.routers.${APP_ID}-livekit-jwt-insecure.priority: 75
      traefik.http.routers.${APP_ID}-livekit-jwt.rule: Host(`${APP_DOMAIN}`) && PathPrefix(`/livekit-jwt`)
      traefik.http.routers.${APP_ID}-livekit-jwt.entrypoints: websecure
      traefik.http.routers.${APP_ID}-livekit-jwt.service: ${APP_ID}-livekit-jwt
      traefik.http.routers.${APP_ID}-livekit-jwt.tls.certresolver: myresolver
      traefik.http.routers.${APP_ID}-livekit-jwt.middlewares: ${APP_ID}-livekit-jwt-stripprefix@docker
      traefik.http.routers.${APP_ID}-livekit-jwt.priority: 75

  # Coturn TURN server for WebRTC relay - Security Hardened
  coturn:
    image: coturn/coturn:4.6.2-r8
    restart: unless-stopped
    network_mode: host
    user: "65534:65534"  # Run as nobody:nobody for security
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /var/run:noexec,nosuid,size=10m
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE  # Required for binding to privileged ports
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    healthcheck:
      test: ["CMD-SHELL", "pidof turnserver || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - TURN_REALM=${APP_DOMAIN}
      - TURN_SECRET=${TURN_SECRET}
      - USER_QUOTA=${USER_QUOTA:-5}
    volumes:
      - ${APP_DATA_DIR}/coturn:/var/lib/coturn:rw
      - ./coturn.conf:/etc/coturn/turnserver.conf:ro
    command: turnserver -c /etc/coturn/turnserver.conf
    labels:
      runtipi.managed: true

  # Tailscale integration (optional)
  tailscale-continuwuity:
    image: lscr.io/linuxserver/tailscale:latest
    hostname: ${TAILSCALE_HOSTNAME:-continuwuity-ts}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      TAILSCALE_AUTH_KEY: ${TAILSCALE_AUTH_KEY}
      TAILSCALE_HOSTNAME: ${TAILSCALE_HOSTNAME:-continuwuity-ts}
    volumes:
      - ${APP_DATA_DIR}/tailscale-state:/config
    networks:
      tipi_main_network:
    depends_on:
      - continuwuity
    profiles:
      - tailscale
    labels:
      runtipi.managed: true

networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true
  continuwuity_network:
    external: false
    ipam:
      config:
        - subnet: 10.128.10.0/24